hosts: #edit (-host or -host:port(for ssh))
  - 127.0.0.1
  - 127.0.0.2:1111
credentials: #edit (format: [user,pw]), attention to BF attacks
  - ['user', 'resu']
checks: #edit (possible values: ping, ssh)
  - ping
  - ssh